# Generated by Django 2.2.7 on 2019-11-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191106_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
    ]
