# Generated by Django 2.2.7 on 2019-11-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_training', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
